model_provider = "fox"
# 可配置gpt-5.4或gpt-5.4
model = "gpt-5.5"
# 可配置high medium low
model_reasoning_effort = "high"
disable_response_storage = true

# foxcode配置
[model_providers.fox]
name = "fox"
base_url = "https://dm-fox.rjj.cc/codex/v1"
wire_api = "responses"
requires_openai_auth = true

[projects."/Users/azurice"]
trust_level = "trusted"

[projects."/Volumes/Files/ship"]
trust_level = "trusted"

[projects."/Volumes/Files/_ranim/ranim"]
trust_level = "trusted"

[projects."/Volumes/Files/_ranim"]
trust_level = "trusted"

[projects."/Volumes/Files/NapCatQQ"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
