font_family JetBrainsMono Nerdfont
font_size 12
background_opacity 0.8

include Catppuccin-Mocha.conf

# Disable default paste_from_selection (primary selection, not clipboard)
map ctrl+shift+s no_op
